apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  DB_NAME: Y3J1ZGRlbW8NCg==
  DB_USER: dXNlcg0K
  DB_PASSWORD: cGFzc3dvcmQNCg==
striungData:
  DB_HOST: postgresdb
  DB_PORT: "5432"
